### ISSUE TITLE
Add validation that references to Cake.Core and Cake.Common is set to private

### ISSUE THREAD

**Issue by AdmiringWorm** [nils-a/CakeContrib.Guidelines#6]
As the recommendation from upstream is always to have `Cake.Core` and `Cake.Common` set as private assets, it would be useful if the guidelines would validate that they indeed are.

Not sure if that is possible through the MSBuild targets, but I would assume it is.

**Comment by nils-a** [comment]
@AdmiringWorm Should this have an opt-out setting? 

Something like 
```xml
<PropertyGroup>
    <CakeContribGuidelinesCakeReferenceOmitPrivateCheck>1</CakeContribGuidelinesCakeReferenceOmitPrivateCheck>
</PropertyGroup>
```

**Comment by AdmiringWorm** [comment]
I do not think it should have any opt-out setting.

but lets hear with @gep13 about that one

**Comment by nils-a** [comment]
This is a first Idea. Always throws an error and has no opt-out setting.

**Comment by gep13** [comment]
The checking for whether or not the references are private is a great idea!  This is something that is recommended through @jericho Cake.AddinDiscoverer.

I want this to be an error so that it is immediately clear to the consumer that it is a problem, I think we should allow an opt-out as well, just in case there is an edge case that needs to be addressed.

So I would say...

Error by default, with option to override.

**Comment by nils-a** [comment]
fixed in https://github.com/nils-a/CakeContrib.Guidelines/pull/7
